/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Channel {
  'id' : ChannelId,
  'country' : string,
  'thumbnailUrl' : string,
  'name' : string,
  'language' : string,
  'streamUrl' : string,
}
export type ChannelId = bigint;
export interface Playlist {
  'id' : PlaylistId,
  'owner' : Principal,
  'name' : string,
  'channels' : Array<ChannelId>,
}
export type PlaylistId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChannel' : ActorMethod<
    [string, string, string, string, string],
    ChannelId
  >,
  'addChannelToPlaylist' : ActorMethod<[PlaylistId, ChannelId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPlaylist' : ActorMethod<[string], PlaylistId>,
  'deleteChannel' : ActorMethod<[ChannelId], undefined>,
  'deletePlaylist' : ActorMethod<[PlaylistId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannels' : ActorMethod<[], Array<Channel>>,
  'getFavourites' : ActorMethod<[], Array<Channel>>,
  'getMyPlaylists' : ActorMethod<[], Array<Playlist>>,
  'getPlaylist' : ActorMethod<[PlaylistId], Playlist>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeChannelFromPlaylist' : ActorMethod<[PlaylistId, ChannelId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleFavourite' : ActorMethod<[ChannelId], boolean>,
  'updateChannel' : ActorMethod<
    [ChannelId, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];